// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Text;
global using global::System.Text.RegularExpressions;
global using global::Newtonsoft.Json;
global using global::stilt.AST;
global using global::stilt.Compilation;
global using global::stilt.Errors;
global using global::stilt.CodeGen;
